server:
  port: 8888

spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/LeeCJ/CloudConfig
          searchPaths: cloud-test
      label: master

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/